version: "3"
services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: your_username # замените эти данные на свои
      POSTGRES_PASSWORD: your_password # замените эти данные на свои
      POSTGRES_DB: test_case2 # замените эти данные на свои, если изменяете - также замените в db.py на 7ой строке
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
